version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    groups:
      terraform-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/bootstrap"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    groups:
      bootstrap-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "actions"
    groups:
      actions-dependencies:
        patterns:
          - "*"
